In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Set the styles to Seaborn
sns.set()
# Import the KMeans module so we can perform k-means clustering with sklearn
from sklearn.cluster import KMeans

In [3]:
playerIntData = pd.read_csv('FYP_final_dataset.csv')
playerIntData.head()

Unnamed: 0  match_id  season                team1  \
0           0         1    2017  Sunrisers Hyderabad   
1           1         1    2017  Sunrisers Hyderabad   
2           2         1    2017  Sunrisers Hyderabad   
3           3         1    2017  Sunrisers Hyderabad   
4           4         1    2017  Sunrisers Hyderabad   

                         team2               winner  result  inning  \
0  Royal Challengers Bangalore  Sunrisers Hyderabad  normal       1   
1  Royal Challengers Bangalore  Sunrisers Hyderabad  normal       1   
2  Royal Challengers Bangalore  Sunrisers Hyderabad  normal       1   
3  Royal Challengers Bangalore  Sunrisers Hyderabad  normal       1   
4  Royal Challengers Bangalore  Sunrisers Hyderabad  normal       1   

          batting_team                 bowling_team  over  ball  \
0  Sunrisers Hyderabad  Royal Challengers Bangalore     1     1   
1  Sunrisers Hyderabad  Royal Challengers Bangalore     1     2   
2  Sunrisers Hyderabad  Royal Challengers Bangalore     1     3   
3  Sunrisers Hyderabad  Royal Challengers Bangalore     1     4   
4  Sunrisers Hyderabad  Royal Challengers Bangalore     1     5   

   is_super_over    batsman non_striker  batsman strike rate  batsman average  \
0              0  DA Warner    S Dhawan           145.696667            62.68   
1              0  DA Warner    S Dhawan           145.696667            62.68   
2              0  DA Warner    S Dhawan           145.696667            62.68   
3              0  DA Warner    S Dhawan           145.696667            62.68   
4              0  DA Warner    S Dhawan           145.696667            62.68   

     bowler  bowler strike rate  bowler average  bowler economy rate  \
0  TS Mills                21.4            30.6                 8.57   
1  TS Mills                21.4            30.6                 8.57   
2  TS Mills                21.4            30.6                 8.57   
3  TS Mills                21.4            30.6                 8.57   
4  TS Mills                21.4            30.6                 8.57   

   wide_runs  bye_runs  legbye_runs  noball_runs  penalty_runs  batsman_runs  \
0          0         0            0            0             0             0   
1          0         0            0            0             0             0   
2          0         0            0            0             0             4   
3          0         0            0            0             0             0   
4          2         0            0            0             0             0   

   extra_runs  total_runs  player_dismissed  dl_applied  
0           0           0                 0           0  
1           0           0                 0           0  
2           0           4                 0           0  
3           0           0                 0           0  
4           2           2                 0           0

In [4]:
playerIntData.columns

Index(['Unnamed: 0', 'match_id', 'season', 'team1', 'team2', 'winner',
       'result', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'is_super_over', 'batsman', 'non_striker', 'batsman strike rate',
       'batsman average', 'bowler', 'bowler strike rate', 'bowler average',
       'bowler economy rate', 'wide_runs', 'bye_runs', 'legbye_runs',
       'noball_runs', 'penalty_runs', 'batsman_runs', 'extra_runs',
       'total_runs', 'player_dismissed', 'dl_applied'],
      dtype='object')

In [5]:
playerIntData = playerIntData.drop(['Unnamed: 0', 'match_id', 'team1', 'team2','wide_runs', 'bye_runs','legbye_runs', 'noball_runs', 'penalty_runs', 'batsman_runs', 'extra_runs'],axis=1)

In [6]:
playerIntData.head()

season               winner  result  inning         batting_team  \
0    2017  Sunrisers Hyderabad  normal       1  Sunrisers Hyderabad   
1    2017  Sunrisers Hyderabad  normal       1  Sunrisers Hyderabad   
2    2017  Sunrisers Hyderabad  normal       1  Sunrisers Hyderabad   
3    2017  Sunrisers Hyderabad  normal       1  Sunrisers Hyderabad   
4    2017  Sunrisers Hyderabad  normal       1  Sunrisers Hyderabad   

                  bowling_team  over  ball  is_super_over    batsman  \
0  Royal Challengers Bangalore     1     1              0  DA Warner   
1  Royal Challengers Bangalore     1     2              0  DA Warner   
2  Royal Challengers Bangalore     1     3              0  DA Warner   
3  Royal Challengers Bangalore     1     4              0  DA Warner   
4  Royal Challengers Bangalore     1     5              0  DA Warner   

  non_striker  batsman strike rate  batsman average    bowler  \
0    S Dhawan           145.696667            62.68  TS Mills   
1    S Dhawan           145.696667            62.68  TS Mills   
2    S Dhawan           145.696667            62.68  TS Mills   
3    S Dhawan           145.696667            62.68  TS Mills   
4    S Dhawan           145.696667            62.68  TS Mills   

   bowler strike rate  bowler average  bowler economy rate  total_runs  \
0                21.4            30.6                 8.57           0   
1                21.4            30.6                 8.57           0   
2                21.4            30.6                 8.57           4   
3                21.4            30.6                 8.57           0   
4                21.4            30.6                 8.57           2   

   player_dismissed  dl_applied  
0                 0           0  
1                 0           0  
2                 0           0  
3                 0           0  
4                 0           0

In [7]:
playerIntData.inning.unique()

array([1, 2, 3, 4, 5], dtype=int64)

In [8]:
inning_filter = playerIntData['inning']<=2
playerIntData = playerIntData[inning_filter]

In [9]:
playerIntData.inning.unique()

array([1, 2], dtype=int64)

In [10]:
playerIntData.batting_team.unique()

array(['Sunrisers Hyderabad', 'Royal Challengers Bangalore',
       'Mumbai Indians', 'Rising Pune Supergiant', 'Gujarat Lions',
       'Kolkata Knight Riders', 'Kings XI Punjab', 'Delhi Daredevils',
       'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants',
       'Delhi Capitals'], dtype=object)

In [11]:
playerIntData.bowling_team.unique()

array(['Royal Challengers Bangalore', 'Sunrisers Hyderabad',
       'Rising Pune Supergiant', 'Mumbai Indians',
       'Kolkata Knight Riders', 'Gujarat Lions', 'Kings XI Punjab',
       'Delhi Daredevils', 'Chennai Super Kings', 'Rajasthan Royals',
       'Deccan Chargers', 'Kochi Tuskers Kerala', 'Pune Warriors',
       'Rising Pune Supergiants', 'Delhi Capitals'], dtype=object)

In [12]:
playerIntData.drop(playerIntData[playerIntData['batting_team']=='Rising Pune Supergiant'].index, inplace = True)
playerIntData.drop(playerIntData[playerIntData['batting_team']=='Rising Pune Supergiants'].index, inplace = True)
playerIntData.drop(playerIntData[playerIntData['batting_team']=='Gujarat Lions'].index, inplace = True)
playerIntData.drop(playerIntData[playerIntData['batting_team']=='Deccan Chargers'].index, inplace = True)
playerIntData.drop(playerIntData[playerIntData['batting_team']=='Kochi Tuskers Kerala'].index, inplace = True)
playerIntData.drop(playerIntData[playerIntData['batting_team']=='Pune Warriors'].index, inplace = True)
playerIntData.drop(playerIntData[playerIntData['bowling_team']=='Rising Pune Supergiant'].index, inplace = True)
playerIntData.drop(playerIntData[playerIntData['bowling_team']=='Rising Pune Supergiants'].index, inplace = True)
playerIntData.drop(playerIntData[playerIntData['bowling_team']=='Gujarat Lions'].index, inplace = True)
playerIntData.drop(playerIntData[playerIntData['bowling_team']=='Deccan Chargers'].index, inplace = True)
playerIntData.drop(playerIntData[playerIntData['bowling_team']=='Kochi Tuskers Kerala'].index, inplace = True)
playerIntData.drop(playerIntData[playerIntData['bowling_team']=='Pune Warriors'].index, inplace = True)

In [13]:
playerIntData.batting_team.unique()

array(['Sunrisers Hyderabad', 'Royal Challengers Bangalore',
       'Delhi Daredevils', 'Kolkata Knight Riders', 'Mumbai Indians',
       'Kings XI Punjab', 'Chennai Super Kings', 'Rajasthan Royals',
       'Delhi Capitals'], dtype=object)

In [14]:
playerIntData.bowling_team.unique()

array(['Royal Challengers Bangalore', 'Sunrisers Hyderabad',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Kings XI Punjab', 'Chennai Super Kings', 'Rajasthan Royals',
       'Delhi Capitals'], dtype=object)

In [15]:
playerIntData.replace(to_replace='Delhi Daredevils',value='Delhi Capitals',inplace=True)

In [16]:
playerIntData.over.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20], dtype=int64)

In [17]:
playerIntData.ball.unique()

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [18]:
playerIntData.is_super_over.unique()

array([0], dtype=int64)

In [19]:
playerIntData = playerIntData.drop(['is_super_over'],axis=1)

In [20]:
playerIntData.total_runs.unique()

array([ 0,  4,  2,  1,  6,  3,  5,  7, 10,  8], dtype=int64)

In [21]:
playerIntData.player_dismissed.unique()

array([0, 1], dtype=int64)

In [22]:
playerIntData.season.unique()

array([2017, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2018,
       2019], dtype=int64)

In [23]:
playerIntData.result.unique()

array(['normal', 'tie', 'no result'], dtype=object)

In [24]:
playerIntData.dl_applied.unique()

array([0, 1], dtype=int64)

In [25]:
playerIntData.columns

Index(['season', 'winner', 'result', 'inning', 'batting_team', 'bowling_team',
       'over', 'ball', 'batsman', 'non_striker', 'batsman strike rate',
       'batsman average', 'bowler', 'bowler strike rate', 'bowler average',
       'bowler economy rate', 'total_runs', 'player_dismissed', 'dl_applied'],
      dtype='object')

In [26]:
playerIntData = playerIntData.drop(['season', 'winner', 'result','dl_applied'],axis=1)

In [27]:
playerIntData.head()

inning         batting_team                 bowling_team  over  ball  \
0       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1     1   
1       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1     2   
2       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1     3   
3       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1     4   
4       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1     5   

     batsman non_striker  batsman strike rate  batsman average    bowler  \
0  DA Warner    S Dhawan           145.696667            62.68  TS Mills   
1  DA Warner    S Dhawan           145.696667            62.68  TS Mills   
2  DA Warner    S Dhawan           145.696667            62.68  TS Mills   
3  DA Warner    S Dhawan           145.696667            62.68  TS Mills   
4  DA Warner    S Dhawan           145.696667            62.68  TS Mills   

   bowler strike rate  bowler average  bowler economy rate  total_runs  \
0                21.4            30.6                 8.57           0   
1                21.4            30.6                 8.57           0   
2                21.4            30.6                 8.57           4   
3                21.4            30.6                 8.57           0   
4                21.4            30.6                 8.57           2   

   player_dismissed  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0

In [28]:
playerIntData.dropna(axis=0)
playerIntData = playerIntData.reset_index(drop=False)
playerIntData.head()

index  inning         batting_team                 bowling_team  over  \
0      0       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1   
1      1       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1   
2      2       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1   
3      3       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1   
4      4       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1   

   ball    batsman non_striker  batsman strike rate  batsman average  \
0     1  DA Warner    S Dhawan           145.696667            62.68   
1     2  DA Warner    S Dhawan           145.696667            62.68   
2     3  DA Warner    S Dhawan           145.696667            62.68   
3     4  DA Warner    S Dhawan           145.696667            62.68   
4     5  DA Warner    S Dhawan           145.696667            62.68   

     bowler  bowler strike rate  bowler average  bowler economy rate  \
0  TS Mills                21.4            30.6                 8.57   
1  TS Mills                21.4            30.6                 8.57   
2  TS Mills                21.4            30.6                 8.57   
3  TS Mills                21.4            30.6                 8.57   
4  TS Mills                21.4            30.6                 8.57   

   total_runs  player_dismissed  
0           0                 0  
1           0                 0  
2           4                 0  
3           0                 0  
4           2                 0

In [29]:
playerIntData = playerIntData.drop(['index'],axis=1)
playerIntData.head()

inning         batting_team                 bowling_team  over  ball  \
0       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1     1   
1       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1     2   
2       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1     3   
3       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1     4   
4       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1     5   

     batsman non_striker  batsman strike rate  batsman average    bowler  \
0  DA Warner    S Dhawan           145.696667            62.68  TS Mills   
1  DA Warner    S Dhawan           145.696667            62.68  TS Mills   
2  DA Warner    S Dhawan           145.696667            62.68  TS Mills   
3  DA Warner    S Dhawan           145.696667            62.68  TS Mills   
4  DA Warner    S Dhawan           145.696667            62.68  TS Mills   

   bowler strike rate  bowler average  bowler economy rate  total_runs  \
0                21.4            30.6                 8.57           0   
1                21.4            30.6                 8.57           0   
2                21.4            30.6                 8.57           4   
3                21.4            30.6                 8.57           0   
4                21.4            30.6                 8.57           2   

   player_dismissed  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0

In [30]:
playerDF = pd.read_csv('PlayerDataCon.csv')
playerDF.head()

Unnamed: 0          Player  Batting Average  Batting Strike Rate  \
0           0  A Ashish Reddy           23.500              162.060   
1           1     A Choudhary           25.000              125.000   
2           2     A Dananjaya            0.000               80.000   
3           3        A Mishra           15.375               65.075   
4           4         A Nehra            0.000               50.000   

   Bowling Average  Bowling Economy Rate  Bowling Strike Rate  \
0           39.000                10.170                23.00   
1           28.800                 8.550                20.20   
2            0.000                11.750                 0.00   
3           26.825                 7.545                21.20   
4           23.365                 8.475                16.55   

                          Team  
0          Sunrisers Hyderabad  
1  Royal Challengers Bangalore  
2               Mumbai Indians  
3               Delhi Capitals  
4          Sunrisers Hyderabad

In [31]:
playerDF = playerDF.drop(['Unnamed: 0'],axis=1)
playerDF.head()

Player  Batting Average  Batting Strike Rate  Bowling Average  \
0  A Ashish Reddy           23.500              162.060           39.000   
1     A Choudhary           25.000              125.000           28.800   
2     A Dananjaya            0.000               80.000            0.000   
3        A Mishra           15.375               65.075           26.825   
4         A Nehra            0.000               50.000           23.365   

   Bowling Economy Rate  Bowling Strike Rate                         Team  
0                10.170                23.00          Sunrisers Hyderabad  
1                 8.550                20.20  Royal Challengers Bangalore  
2                11.750                 0.00               Mumbai Indians  
3                 7.545                21.20               Delhi Capitals  
4                 8.475                16.55          Sunrisers Hyderabad

In [32]:
x1 = playerDF.iloc[:,1:3]
x1.head()

Batting Average  Batting Strike Rate
0           23.500              162.060
1           25.000              125.000
2            0.000               80.000
3           15.375               65.075
4            0.000               50.000

In [33]:
kmeans = KMeans(15)

In [34]:
kmeans.fit(x1)

KMeans(n_clusters=15)

In [35]:
identified_batting_clusters = kmeans.fit_predict(x1)
identified_batting_clusters

array([11,  5,  3,  3,  8,  9,  5,  5,  0, 11,  1, 10,  1,  8,  6,  3, 14,
        5, 12,  1,  7,  5,  2,  7,  3,  7,  8, 14,  1, 12,  5, 10,  3, 11,
        3, 11,  5,  5,  5,  2,  2,  2,  0,  7,  1, 10,  0,  7, 12,  5,  9,
        6,  5,  7,  5, 12, 12,  3, 12,  0,  7,  5,  5, 14,  6,  5,  7,  8,
        8,  2,  0, 14,  1,  6,  6,  8,  0,  4,  4,  0,  1,  8, 14,  5,  1,
        1,  5,  2,  8,  3,  6,  7,  9, 12,  7,  5, 10,  7, 10,  7,  0,  2,
       10,  2,  2, 11,  7,  5,  9,  7, 12,  3,  6,  3, 14,  3,  7,  1,  7,
       14,  2,  8, 14, 14,  7,  5,  5,  5,  1,  6, 14, 10,  7, 14,  6,  4,
        6, 14, 11,  3,  0,  5,  9,  0, 12,  0,  8,  3,  7,  2,  6,  8,  0,
        3,  0,  7,  3,  0,  0, 10,  0,  6, 10,  7,  0,  2, 14,  6, 10, 13,
        6, 14, 10, 14,  5,  5, 14,  6,  1, 14,  2,  6, 10, 12,  8,  8,  6,
        5,  0,  7,  7,  7,  1,  7,  6,  7,  5,  6, 10,  6, 12, 11,  2, 13,
        5,  5,  5, 10,  6,  5,  5,  6, 10,  6, 14,  5, 14, 14,  0,  6,  1,
        7,  7,  3, 10,  0

In [36]:
playerData_with_clusters = playerDF.copy()
playerData_with_clusters['Batting Cluster'] = identified_batting_clusters
playerData_with_clusters.head()

Player  Batting Average  Batting Strike Rate  Bowling Average  \
0  A Ashish Reddy           23.500              162.060           39.000   
1     A Choudhary           25.000              125.000           28.800   
2     A Dananjaya            0.000               80.000            0.000   
3        A Mishra           15.375               65.075           26.825   
4         A Nehra            0.000               50.000           23.365   

   Bowling Economy Rate  Bowling Strike Rate                         Team  \
0                10.170                23.00          Sunrisers Hyderabad   
1                 8.550                20.20  Royal Challengers Bangalore   
2                11.750                 0.00               Mumbai Indians   
3                 7.545                21.20               Delhi Capitals   
4                 8.475                16.55          Sunrisers Hyderabad   

   Batting Cluster  
0               11  
1                5  
2                3  
3                3  
4                8

In [37]:
playerData_with_clusters['Batting Cluster'].value_counts()

5     34
7     30
6     27
14    22
0     20
3     18
10    17
1     16
8     14
2     14
12    11
11     7
9      6
4      3
13     2
Name: Batting Cluster, dtype: int64

In [38]:
x2 = playerDF.iloc[:,3:6]
x2.head()

Bowling Average  Bowling Economy Rate  Bowling Strike Rate
0           39.000                10.170                23.00
1           28.800                 8.550                20.20
2            0.000                11.750                 0.00
3           26.825                 7.545                21.20
4           23.365                 8.475                16.55

In [39]:
kmeans = KMeans(15)

In [40]:
kmeans.fit(x2)

KMeans(n_clusters=15)

In [41]:
identified_bowling_clusters = kmeans.fit_predict(x2)
identified_bowling_clusters

array([10,  2,  6,  2, 11,  0,  0,  6,  0, 11,  9,  0,  0,  7,  0,  0,  0,
        9,  5, 10,  5,  0, 14,  6,  5, 10, 11,  2, 11,  2, 10,  0, 11, 12,
       14,  9,  0, 10,  0,  0, 14,  2,  7,  6, 14,  2, 11, 10,  6,  0,  0,
       10,  5,  7, 11, 11,  0,  0,  7, 11,  5,  0,  0,  0,  0,  0, 10,  2,
        6,  5, 14,  0, 10, 10,  0,  1, 10,  6,  5,  0, 11, 11,  2,  0, 14,
        9, 11,  0,  2, 11,  0,  0,  0,  1, 10,  5,  9, 11,  4,  7, 11,  6,
        2,  0,  2,  8, 14,  0,  0, 11,  0,  2,  0,  5,  5, 10,  5,  1,  8,
        0,  6, 10,  9,  2, 12,  0,  0,  0,  6,  3, 12,  0, 13,  2, 11,  0,
        0,  6, 10, 10,  6,  7,  0,  0, 10,  9,  2,  9, 11,  0, 14, 10,  2,
        0,  0,  5,  0,  9,  6,  7,  0,  0, 11,  6,  2,  0,  3,  0, 10,  2,
       12, 12, 11, 11,  2,  0, 11,  0,  0,  0,  0,  0, 11,  6, 10, 11,  0,
        0,  5,  2, 11,  6,  7,  7,  0, 10,  0,  0, 12,  0,  2,  2,  6,  2,
        0,  0,  0, 10,  0,  2,  0,  0,  7,  0,  0,  0,  2, 10,  1,  0,  2,
       12,  7, 10, 12,  5

In [42]:
playerData_with_clusters['Bowling Cluster'] = identified_bowling_clusters
playerData_with_clusters.head()

Player  Batting Average  Batting Strike Rate  Bowling Average  \
0  A Ashish Reddy           23.500              162.060           39.000   
1     A Choudhary           25.000              125.000           28.800   
2     A Dananjaya            0.000               80.000            0.000   
3        A Mishra           15.375               65.075           26.825   
4         A Nehra            0.000               50.000           23.365   

   Bowling Economy Rate  Bowling Strike Rate                         Team  \
0                10.170                23.00          Sunrisers Hyderabad   
1                 8.550                20.20  Royal Challengers Bangalore   
2                11.750                 0.00               Mumbai Indians   
3                 7.545                21.20               Delhi Capitals   
4                 8.475                16.55          Sunrisers Hyderabad   

   Batting Cluster  Bowling Cluster  
0               11               10  
1                5                2  
2                3                6  
3                3                2  
4                8               11

In [43]:
playerData_with_clusters['Bowling Cluster'].value_counts()

0     78
2     28
11    27
10    26
6     17
5     15
7     11
9     10
14     9
12     8
1      6
8      2
3      2
13     1
4      1
Name: Bowling Cluster, dtype: int64

In [44]:
# playerIntData.sort_index().sort_index(axis=1)
# playerData_with_clusters.sort_index().sort_index(axis=1)
playerIntData['batsman cluster']=np.nan
for i in range(playerIntData.shape[0]):
    for j in range(playerData_with_clusters.shape[0]):
        if playerIntData['batsman'][i] == playerData_with_clusters['Player'][j]:
            playerIntData['batsman cluster'][i] = playerData_with_clusters['Batting Cluster'][j]
            break
playerIntData.head()

<ipython-input-44-0ca1270fe94b>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerIntData['batsman cluster'][i] = playerData_with_clusters['Batting Cluster'][j]


inning         batting_team                 bowling_team  over  ball  \
0       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1     1   
1       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1     2   
2       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1     3   
3       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1     4   
4       1  Sunrisers Hyderabad  Royal Challengers Bangalore     1     5   

     batsman non_striker  batsman strike rate  batsman average    bowler  \
0  DA Warner    S Dhawan           145.696667            62.68  TS Mills   
1  DA Warner    S Dhawan           145.696667            62.68  TS Mills   
2  DA Warner    S Dhawan           145.696667            62.68  TS Mills   
3  DA Warner    S Dhawan           145.696667            62.68  TS Mills   
4  DA Warner    S Dhawan           145.696667            62.68  TS Mills   

   bowler strike rate  bowler average  bowler economy rate  total_runs  \
0                21.4            30.6                 8.57           0   
1                21.4            30.6                 8.57           0   
2                21.4            30.6                 8.57           4   
3                21.4            30.6                 8.57           0   
4                21.4            30.6                 8.57           2   

   player_dismissed  batsman cluster  
0                 0              9.0  
1                 0              9.0  
2                 0              9.0  
3                 0              9.0  
4                 0              9.0

In [ ]:
# playerIntData.sort_index().sort_index(axis=1)
# playerData_with_clusters.sort_index().sort_index(axis=1)
playerIntData['bowler cluster']=np.nan
for i in range(playerIntData.shape[0]):
    for j in range(playerData_with_clusters.shape[0]):
        if playerIntData['bowler'][i] == playerData_with_clusters['Player'][j]:
            playerIntData['bowler cluster'][i] = playerData_with_clusters['Bowling Cluster'][j]
            break
playerIntData.head()

<ipython-input-45-0bf0b011641d>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerIntData['bowler cluster'][i] = playerData_with_clusters['Bowling Cluster'][j]


In [ ]:
dataset = playerIntData.drop(['batsman','non_striker','batsman strike rate','batsman average','bowler','bowler strike rate','bowler average','bowler economy rate'],axis=1)
dataset.head()

In [ ]:
dataset=pd.get_dummies(dataset,columns=['batting_team','bowling_team'])
dataset.head()

In [ ]:
dataset.describe()

In [ ]:
dataset = dataset.dropna(axis=0)

In [ ]:
dataset.columns

In [ ]:
from sklearn.model_selection import train_test_split

X = dataset[['inning', 'over','ball',
       'batsman cluster', 'bowler cluster']]
y = dataset['total_runs']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=False)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100)

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

In [ ]:
y_pred

In [ ]:
pred_df = pd.DataFrame(y_pred)

In [ ]:
from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

In [ ]:
feature_imp = pd.Series(clf.feature_importances_,index=X_train.columns).sort_values(ascending=False)
feature_imp

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
# Creating a bar plot
sns.barplot(x=feature_imp, y=feature_imp.index)
# Add labels to your graph
plt.xlabel('Feature Importance Score')
plt.ylabel('Features')
plt.title("Visualizing Important Features")
plt.legend()
plt.show()

In [ ]:
dataset.player_dismissed.value_counts()

In [ ]:
player_dismissed_data = dataset.copy()

In [ ]:
datasetV2 = player_dismissed_data[player_dismissed_data['player_dismissed']==0].sample(n=3307)

In [ ]:
datasetV2 = datasetV2.append(player_dismissed_data[player_dismissed_data['player_dismissed']==1])

In [ ]:
datasetV2.player_dismissed.value_counts()

In [ ]:
from sklearn.model_selection import train_test_split

X1 = dataset[['inning', 'over','ball',
       'batsman cluster', 'bowler cluster']]
y1 = dataset['player_dismissed']

X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.3, shuffle=True)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

clf1 = RandomForestClassifier(n_estimators=100)

clf1.fit(X_train1,y_train1)

y_pred1 = clf1.predict(X_test1)

In [ ]:
from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(y_test1, y_pred1))

In [ ]:
feature_imp1 = pd.Series(clf1.feature_importances_,index=X_train.columns).sort_values(ascending=False)
feature_imp1

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
# Creating a bar plot
sns.barplot(x=feature_imp1, y=feature_imp1.index)
# Add labels to your graph
plt.xlabel('Feature Importance Score')
plt.ylabel('Features')
plt.title("Visualizing Important Features")
plt.legend()
plt.show()

In [ ]:
team1 = ['RG Sharma','E Lewis','SA Yadav','Ishan Kishan','KA Pollard','HH Pandya','KH Pandya','J Yadav','MJ McClenaghan','SL Malinga','JJ Bumrah']
team2 = ['S Dhawan','JJ Roy','SS Iyer','RR Pant','R Tewatia','CH Morris','AR Patel','HV Patel','I Sharma','PJ Cummins','K Rabada']
batClustT1={}
bowlClustT1={}
batClustT2={}
bowlClustT2={}
for i in range(11):
    for j in range(playerData_with_clusters.shape[0]):
        if team1[i]==playerData_with_clusters['Player'][j]:
            batClustT1[team1[i]]=playerData_with_clusters['Batting Cluster'][j]
            bowlClustT1[team1[i]]=playerData_with_clusters['Bowling Cluster'][j]
        if team2[i]==playerData_with_clusters['Player'][j]:
            batClustT2[team2[i]]=playerData_with_clusters['Batting Cluster'][j]
            bowlClustT2[team2[i]]=playerData_with_clusters['Bowling Cluster'][j]

team1BatClust=list(batClustT1.values())
team2BatClust=list(batClustT2.values())
team1BowlClust=list(bowlClustT1.values())
team2BowlClust=list(bowlClustT2.values())

In [ ]:
overs = 1
balls = 1
runs=0
wickets = 0
innings=1
indexOfBatsmanOnStrike=0
indexOfNonStriker = 1
indexOfWicket = 1
indexOfBowler=-1
print("overs","balls","runs","total runs","wickets","total wickets",sep=" |")
while overs<=20 and wickets<=10:
    while balls<=6 and wickets<=10:
        arr = np.array([[innings,overs,balls,team1BatClust[indexOfBatsmanOnStrike],team2BowlClust[indexOfBowler]]])
        runs_pred = clf.predict(arr)
        wickets_pred = clf1.predict(arr)
        runs +=runs_pred[0]
        wickets +=wickets_pred[0]
        print(overs,balls,runs_pred[0],runs,wickets_pred[0],wickets,sep="\t|")
        if wickets_pred==1:
            indexOfWicket+=1
            indexOfBatsmanOnStrike = indexOfWicket
        if runs_pred == 1 or runs_pred == 3:
            temp = indexOfBatsmanOnStrike
            indexOfBatsmanOnStrike=indexOfNonStriker
            indexOfNonStriker=temp
        balls+=1
    temp = indexOfBatsmanOnStrike
    indexOfBatsmanOnStrike=indexOfNonStriker
    indexOfNonStriker=temp
    overs+=1
    balls=1
    indexOfBowler-=1
    if indexOfBowler==-6:
        indexOfBowler=-1

In [ ]:
overs = 1
balls = 1
runs=0
wickets = 0
innings=1
indexOfBatsmanOnStrike=0
indexOfNonStriker = 1
indexOfWicket = 1
indexOfBowler=-1
print("overs","balls","runs","total runs","wickets","total wickets",sep=" |")
while overs<=20 and wickets<=10:
    while balls<=6 and wickets<=10:
        arr = np.array([[innings,overs,balls,team2BatClust[indexOfBatsmanOnStrike],team1BowlClust[indexOfBowler]]])
        runs_pred = clf.predict(arr)
        wickets_pred = clf1.predict(arr)
        runs +=runs_pred[0]
        wickets +=wickets_pred[0]
        print(overs,balls,runs_pred[0],runs,wickets_pred[0],wickets,sep="\t|")
        if wickets_pred==1:
            indexOfWicket+=1
            indexOfBatsmanOnStrike = indexOfWicket
        if runs_pred == 1 or runs_pred == 3:
            temp = indexOfBatsmanOnStrike
            indexOfBatsmanOnStrike=indexOfNonStriker
            indexOfNonStriker=temp
        balls+=1
    temp = indexOfBatsmanOnStrike
    indexOfBatsmanOnStrike=indexOfNonStriker
    indexOfNonStriker=temp
    overs+=1
    balls=1
    indexOfBowler-=1
    if indexOfBowler==-6:
        indexOfBowler=-1